apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceproxies.stable.dfds.cloud
spec:
  group: stable.dfds.cloud
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                services:
                  type: string
  scope: Namespaced
  names:
    plural: serviceproxies
    singular: serviceproxy
    kind: ServiceProxy
    shortNames:
    - sp
    - svcp