apiVersion: stable.dfds.cloud/v1alpha1
kind: ServiceProxy
metadata:
  name: "selfservice-gateway"
spec:
  services:
    - name: "capsvc"
      lookupServiceName: "Capability-Service"
      lookupServiceNamespace: "selfservice"
    - name: "harald"
      lookupServiceName: "harald"
      lookupServiceNamespace: "selfservice-herald-vbqkr"
