---
apiVersion: v1
kind: Service
metadata:
  name: my-service-name
  annotations: 
    dfds.serviceproxy.kubernetes.io/identifier: "my-service-id"
spec:
  selector:
    app: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376