apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceproxy-operator
  namespace: developerautomation-xavgy
  annotations:
    iam.amazonaws.com/role: arn:aws:iam::642375522597:role/ServiceProxy-dyndb
  labels:
    project: developerautomation
    department: cloudengineering
    component: serviceproxy
    app: serviceproxy-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceproxy-operator
  template:
    metadata:
      labels:
        project: developerautomation
        department: cloudengineering
        app: serviceproxy-operator
    spec:
      priorityClassName: selfservice
      serviceAccountName: serviceproxy-operator
      containers:
      - name: serviceproxy-operator
        image: 642375522597.dkr.ecr.eu-west-1.amazonaws.com/dfds.developerautomation-xavgy.serviceproxy:operator-#(Build.BuildId)
        env:
          SERVICEPROXY_ENABLE_SERVICEPROXY_CONTROLLER: false
        ports:
        - containerPort: 8090
          name: api
        - containerPort: 8080
          name: metrics
        resources:
          requests:
            memory: "200Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "200m"