apiVersion: v1
kind: Service
metadata:
  name: serviceproxy-operator-service
  namespace: developerautomation-xavgy
  labels:
    app: serviceproxy-operator
    project: developerautomation
    department: cloudengineering
    component: serviceproxy
spec:
  ports:
  - name: external
    port: 80
    targetPort: api
  - name: metrics
    port: 8080
    targetPort: 8080
  selector:
    app: serviceproxy-operator