apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developerautomation-serviceproxy-serviceproxies-admin-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: serviceproxy-admin
subjects:
- kind: Group
  name: developerautomation-xavgy
- kind: ServiceAccount
  name: serviceproxy-operator
  namespace: developerautomation-xavgy
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developerautomation-serviceproxy-read-watch-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: serviceproxy-read-and-watch
subjects:
- kind: Group
  name: developerautomation-xavgy
- kind: ServiceAccount
  name: serviceproxy-operator
  namespace: developerautomation-xavgy