apiVersion: dynamodb.aws.crossplane.io/v1alpha1
kind: Table
metadata:
  name: serviceproxy-services
  namespace: rifis-test
spec:
  providerConfigRef:
    name: rifis-test-aws
  writeConnectionSecretToRef:
    name: serviceproxy-dynamodb-table-services
    namespace: rifis-test
  forProvider:
    region: eu-west-1
    keySchema:
      - attributeName: servicename
        keyType: HASH
    attributeDefinitions:
      - attributeName: servicename
        attributeType: S 
    provisionedThroughput:
      readCapacityUnits: 1
      writeCapacityUnits: 1